// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/freddy50806/gRPCTestWithGomock/Streaming/proto (interfaces: ExampleServiceClient,ExampleService_DisplayLinesClient)

// Package mock_proto is a generated GoMock package.
package mock_proto

import (
	context "context"
	reflect "reflect"

	proto "github.com/freddy50806/gRPCTestWithGomock/Streaming/proto"
	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
	metadata "google.golang.org/grpc/metadata"
)

// MockExampleServiceClient is a mock of ExampleServiceClient interface
type MockExampleServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockExampleServiceClientMockRecorder
}

// MockExampleServiceClientMockRecorder is the mock recorder for MockExampleServiceClient
type MockExampleServiceClientMockRecorder struct {
	mock *MockExampleServiceClient
}

// NewMockExampleServiceClient creates a new mock instance
func NewMockExampleServiceClient(ctrl *gomock.Controller) *MockExampleServiceClient {
	mock := &MockExampleServiceClient{ctrl: ctrl}
	mock.recorder = &MockExampleServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockExampleServiceClient) EXPECT() *MockExampleServiceClientMockRecorder {
	return m.recorder
}

// DisplayLines mocks base method
func (m *MockExampleServiceClient) DisplayLines(arg0 context.Context, arg1 *proto.Request, arg2 ...grpc.CallOption) (proto.ExampleService_DisplayLinesClient, error) {
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DisplayLines", varargs...)
	ret0, _ := ret[0].(proto.ExampleService_DisplayLinesClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DisplayLines indicates an expected call of DisplayLines
func (mr *MockExampleServiceClientMockRecorder) DisplayLines(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisplayLines", reflect.TypeOf((*MockExampleServiceClient)(nil).DisplayLines), varargs...)
}

// MockExampleService_DisplayLinesClient is a mock of ExampleService_DisplayLinesClient interface
type MockExampleService_DisplayLinesClient struct {
	ctrl     *gomock.Controller
	recorder *MockExampleService_DisplayLinesClientMockRecorder
}

// MockExampleService_DisplayLinesClientMockRecorder is the mock recorder for MockExampleService_DisplayLinesClient
type MockExampleService_DisplayLinesClientMockRecorder struct {
	mock *MockExampleService_DisplayLinesClient
}

// NewMockExampleService_DisplayLinesClient creates a new mock instance
func NewMockExampleService_DisplayLinesClient(ctrl *gomock.Controller) *MockExampleService_DisplayLinesClient {
	mock := &MockExampleService_DisplayLinesClient{ctrl: ctrl}
	mock.recorder = &MockExampleService_DisplayLinesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockExampleService_DisplayLinesClient) EXPECT() *MockExampleService_DisplayLinesClientMockRecorder {
	return m.recorder
}

// CloseSend mocks base method
func (m *MockExampleService_DisplayLinesClient) CloseSend() error {
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend
func (mr *MockExampleService_DisplayLinesClientMockRecorder) CloseSend() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockExampleService_DisplayLinesClient)(nil).CloseSend))
}

// Context mocks base method
func (m *MockExampleService_DisplayLinesClient) Context() context.Context {
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context
func (mr *MockExampleService_DisplayLinesClientMockRecorder) Context() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockExampleService_DisplayLinesClient)(nil).Context))
}

// Header mocks base method
func (m *MockExampleService_DisplayLinesClient) Header() (metadata.MD, error) {
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(metadata.MD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Header indicates an expected call of Header
func (mr *MockExampleService_DisplayLinesClientMockRecorder) Header() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockExampleService_DisplayLinesClient)(nil).Header))
}

// Recv mocks base method
func (m *MockExampleService_DisplayLinesClient) Recv() (*proto.Reply, error) {
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*proto.Reply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv
func (mr *MockExampleService_DisplayLinesClientMockRecorder) Recv() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockExampleService_DisplayLinesClient)(nil).Recv))
}

// RecvMsg mocks base method
func (m *MockExampleService_DisplayLinesClient) RecvMsg(arg0 interface{}) error {
	ret := m.ctrl.Call(m, "RecvMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg
func (mr *MockExampleService_DisplayLinesClientMockRecorder) RecvMsg(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockExampleService_DisplayLinesClient)(nil).RecvMsg), arg0)
}

// SendMsg mocks base method
func (m *MockExampleService_DisplayLinesClient) SendMsg(arg0 interface{}) error {
	ret := m.ctrl.Call(m, "SendMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg
func (mr *MockExampleService_DisplayLinesClientMockRecorder) SendMsg(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockExampleService_DisplayLinesClient)(nil).SendMsg), arg0)
}

// Trailer mocks base method
func (m *MockExampleService_DisplayLinesClient) Trailer() metadata.MD {
	ret := m.ctrl.Call(m, "Trailer")
	ret0, _ := ret[0].(metadata.MD)
	return ret0
}

// Trailer indicates an expected call of Trailer
func (mr *MockExampleService_DisplayLinesClientMockRecorder) Trailer() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trailer", reflect.TypeOf((*MockExampleService_DisplayLinesClient)(nil).Trailer))
}
